### ISSUE TITLE
Have some questions on 'Network 2'

### ISSUE THREAD

**Issue by 2gunsu** [longyunf/rc-pda#1]
Thank you so much for sharing your valuable research and code.

According to Table 2 and 3 in the paper, [Sparse-to-Dense](https://ieeexplore.ieee.org/document/8460184) [29] and [MSG-CHN](https://ieeexplore.ieee.org/document/9093407) [25] seem to be used as the structure of 'Network 2'.
But when I look at the code ```train_depth.py```, I can't find the parts for these two models, only 'PyramidCNN' exists.

Where can I find the code for the above two models?
Thank you.

**Comment by longyunf** [comment]
For better performance, we implement the depth completion scheme of [29] with Pyramid Network, not exactly the same as the original network used in [29]. In our implementation, we still follow the principle of [29], i.e using depths and RGB as different channels of the input tensor. 

I added the code of depth completion for [25].

**Comment by 2gunsu** [comment]
I really appreciate for your kind help. Have a nice day!
