### ISSUE TITLE
Train my own dataset

### ISSUE THREAD

**Issue by stanny880913** [longyunf/rc-pda#10]
If i had my own dataset，many pair of jpg and pcd file，is it possible for me to train my own data? amybr generate custom prepared_data.h5 and mer_2_30_5_0.5.h5 file?

**Comment by longyunf** [comment]
Training with your own data is feasible if you have annotations of objects.
________________________________
From: StannyHo ***@***.***>
Sent: Monday, June 12, 2023 6:04 AM
To: longyunf/rc-pda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [longyunf/rc-pda] Train my own dataset (Issue #10)


If i had my own dataset，many pair of jpg and pcd file，is it possible for me to train my own data? amybr generate custom prepared_data.h5 and mer_2_30_5_0.5.h5 file?

**Comment by stanny880913** [comment]
> 

Sorry for disturbing you,but if i only have camera and radar data,is it posible to predict depth map?According to the papers and codes, both training and Infernece seems to be need to use lidar data!! thank you
