### ISSUE TITLE
Question on the loss function

### ISSUE THREAD

**Issue by zzangjinsun** [longyunf/rc-pda#3]
Hi Long,

I have a small question on the loss function in the paper (i.e. Eq. 2).

![image](https://user-images.githubusercontent.com/20081006/125193795-55094580-e289-11eb-8e1e-5169cc57d04c.png)

I am a bit confused now and think it should be: 

![image](https://user-images.githubusercontent.com/20081006/125193891-cba64300-e289-11eb-9d6b-95df2bd93118.png)

Moreover, in the implementation, I found two weights w0 and w1:

https://github.com/longyunf/rc-pda/blob/d90ed4b6cf2c5d3809b41b34704698ec753f75b0/scripts/train_pda.py#L23-L37

Are they for balancing between valid/invalid pixels?

Thx!

**Comment by longyunf** [comment]
1. The deduction of Eq. (2) is
![image](https://user-images.githubusercontent.com/56092152/125891167-460eddd4-16f9-46f0-9836-4e5e4d8f909b.png)

2. w0 and w1 are used to balance the loss for positive and negative pixels.

**Comment by zzangjinsun** [comment]
Thank you for your kind explanation!  :)
